[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}

[build]
  command = "cd /opt/build/repo/client npm install && npm run build"
