[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}

[build]
  command = "npm install && npm run build"
  functions = "functions"
